### ISSUE TITLE
Request failed without any error message

### ISSUE THREAD

**Issue by vt107** [Xeukxz/get-twitter-media#2]
> (async () => {
    try {
        const getTwitterMedia = require('get-twitter-media');
        console.log('1')
        let media = await getTwitterMedia("https://twitter.com/msVrXx/status/1577289590746091520", false);
        console.log('2')
        console.log({media});
    } catch (e) {
        console.error('error', e);
    }
})();

Above code does not work. I've checked the source and detected that this library used ssstwitter for getting video info. This is why this lib is not working anymore...

**Comment by Xeukxz** [comment]
Im pretty sure this stopped working the day after i made it due to ssstwitter making changes to their site, after which i just used the official twitter api and abandoned this, didnt think anyone would come across it but i guess due to twitters api updates people are searching quite deep for solutions. Hope u didnt waste too much time on this.

**Comment by vt107** [comment]
Yeah I only spent few minutes. BTW do you have any way to get Instagram videos from link (without cookie)? I've been searching for weeks but there is no solution...

**Comment by MrSrv7** [comment]
![image](https://github.com/Xeukxz/get-twitter-media/assets/54573655/cc437579-4e42-46fc-abca-4be922ffc252)

It is working for me, though.

```
const getTwitterMedia = async (req, res) => {
  try {
    let result =  await getTwitterVideo("https://twitter.com/msVrXx/status/1577289590746091520", false);
    return res.status(200).json({ result });
  } catch (error) {
    return res.status(500).json({ error });
  }
};
```
